/*
 * File: app/view/EditToolsViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('eLearning.view.EditToolsViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.edittools',

    show: function(opts) {
        opts = Ext.applyIf(opts || {}, {
            component: null
        });

        var me = this,
            view = me.getView();

        me._opts = opts;

        view.down('#nfScore').setValue(opts.component._opts.score || 0);
        view.down('#chRequired').setValue(opts.component._opts.required || false);

        view.showBy(opts.component, 'tl-tr?');
    },

    edit: function(button, e) {
        this._opts.component.fireEvent('_edit');
    },

    duplicate: function(button, e) {
        this._opts.component.fireEvent('_duplicate');
    },

    delete: function(button, e) {
        this._opts.component.fireEvent('_delete');
    },

    onNfScoreChange: function(field, newValue, oldValue, eOpts) {
        this._opts.component._opts.score = newValue;
    },

    onChRequiredChange: function(field, newValue, oldValue, eOpts) {
        this._opts.component._opts.required = newValue;
    }

});
