/*
 * File: app/view/SourceView.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('eLearning.view.SourceView', {
    extend: 'Ext.window.Window',
    alias: 'widget.sourceview',

    requires: [
        'eLearning.view.SourceViewViewModel',
        'eLearning.view.SourceViewViewController',
        'Ext.container.Container'
    ],

    controller: 'sourceview',
    viewModel: {
        type: 'sourceview'
    },
    modal: true,
    height: 600,
    width: 1000,
    layout: 'fit',
    title: 'Source',
    maximizable: true,

    items: [
        {
            xtype: 'container',
            reference: 'source',
            scrollable: 'both'
        }
    ]

});