/*
 * File: app/view/TextEditor.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('eLearning.view.TextEditor', {
    extend: 'Ext.window.Window',
    alias: 'widget.texteditor',

    requires: [
        'eLearning.view.TextEditorViewModel',
        'eLearning.view.TextEditorViewController',
        'Ext.form.field.HtmlEditor',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'texteditor',
    viewModel: {
        type: 'texteditor'
    },
    modal: true,
    height: 600,
    itemId: 'texteditor',
    width: 1000,
    layout: 'fit',
    title: 'Text editor',

    items: [
        {
            xtype: 'htmleditor',
            reference: 'htmlEditor',
            itemId: 'htmlEditor',
            fieldLabel: ''
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            ui: 'footer',
            layout: {
                type: 'hbox',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    handler: 'btnSaveHandler',
                    itemId: 'btnSave',
                    text: 'Save'
                },
                {
                    xtype: 'button',
                    handler: 'btnCancelHandler',
                    itemId: 'btnCancel',
                    text: 'Cancel'
                }
            ]
        }
    ]

});