/*
 * File: app/model/Program.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('eLearning.model.Program', {
	extend: 'Ext.data.Model',

	requires: [
		'Ext.data.field.String',
		'Ext.data.field.Date',
		'Ext.data.field.Number',
		'Ext.data.field.Boolean'
	],

	fields: [
		{
			type: 'string',
			name: 'id',
			unique: true
		},
		{
			type: 'int',
			name: 'programId'
		},
		{
			name: 'name'
		},
		{
			type: 'int',
			name: 'categoryId'
		},
		{
			name: 'description'
		},
		{
			type: 'date',
			name: 'validFrom',
			dateWriteFormat: 'c'
		},
		{
			type: 'date',
			name: 'validTo',
			dateWriteFormat: 'c'
		},
		{
			type: 'float',
			name: 'completionTime'
		},
		{
			type: 'int',
			name: 'maxAttemptsTrainingMode'
		},
		{
			type: 'int',
			name: 'maxAttemptsScoreMode'
		},
		{
			name: 'passScore'
		},
		{
			name: 'certificateFileName'
		},
		{
			type: 'boolean',
			name: 'active'
		},
		{
			type: 'int',
			name: 'createdById'
		},
		{
			type: 'int',
			name: 'createdAtId'
		},
		{
			type: 'date',
			name: 'created'
		},
		{
			type: 'date',
			name: 'lastChanges'
		},
		{
			name: 'changed'
		},
		{
			type: 'int',
			name: 'lastChangeLogId'
		}
	]
});