/*
 * File: app/view/EditTools.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('eLearning.view.EditTools', {
    extend: 'Ext.window.Window',
    alias: 'widget.edittools',

    requires: [
        'eLearning.view.EditToolsViewModel',
        'eLearning.view.EditToolsViewController',
        'Ext.button.Button',
        'Ext.form.field.Number',
        'Ext.form.field.Checkbox'
    ],

    controller: 'edittools',
    viewModel: {
        type: 'edittools'
    },
    resizable: false,
    width: 150,
    defaults: {
        anchor: '100%',
        margin: 2
    },
    layout: 'anchor',
    bodyPadding: 3,
    closeAction: 'hide',
    header: false,
    title: 'Component',

    items: [
        {
            xtype: 'button',
            handler: 'edit',
            iconCls: 'x-fa fa-edit',
            text: 'Edit'
        },
        {
            xtype: 'button',
            handler: 'duplicate',
            iconCls: 'x-fa fa-clone',
            text: 'Duplicate'
        },
        {
            xtype: 'button',
            handler: 'delete',
            iconCls: 'x-fa fa-trash-o',
            text: 'Delete'
        },
        {
            xtype: 'numberfield',
            anchor: '100%',
            itemId: 'nfScore',
            fieldLabel: 'Score',
            labelAlign: 'top',
            labelWidth: 50,
            listeners: {
                change: 'onNfScoreChange'
            }
        },
        {
            xtype: 'checkboxfield',
            anchor: '100%',
            itemId: 'chRequired',
            fieldLabel: '',
            boxLabel: 'Required',
            listeners: {
                change: 'onChRequiredChange'
            }
        }
    ]

});