/*
 * File: app/view/EditSlidesViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('eLearning.view.EditSlidesViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.editslides',

    requires: [
        'Ext.data.TreeStore',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json',
        'Ext.data.writer.Json'
    ],

    stores: {
        TreeStoreSlides: {
            type: 'tree',
            model: 'eLearning.model.Slide',
            defaultRootText: 'Slides',
            parentIdProperty: 'parentId',
            root: {
                expanded: true,
                loaded: true
            },
            proxy: {
                type: 'rest',
                api: {
                    create: '/Pub/Pages',
                    read: '/Pub/Pages',
                    update: '/POST/Pub/Pages',
                    destroy: '/Pub/Pages'
                },
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                },
                writer: {
                    type: 'json',
                    writeAllFields: true,
                    rootProperty: 'data'
                }
            }
        },
        QuestionsStoreSlides: {
            model: 'eLearning.model.Question',
            proxy: {
                type: 'ajax',
                api: {
                    create: '/Pub/Questions',
                    read: '/Pub/Questions',
                    update: '/POST/Pub/Questions',
                    destroy: '/Pub/Questions'
                },
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            }
        },
        PersonAnswers: {
            model: 'eLearning.model.PersonAnswers',
            proxy: {
                type: 'ajax',
                api: {
                    create: '/Pub/PersonAnswers',
                    read: '/Pub/PersonAnswers',
                    update: '/POST/Pub/PersonAnswers',
                    destroy: '/Pub/PersonAnswers'
                },
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            }
        },
        PersonPrograms: {
            model: 'eLearning.model.PersonPrograms',
            proxy: {
                type: 'ajax',
                api: {
                    create: '/Pub/PersonPrograms',
                    read: '/Pub/PersonPrograms',
                    update: '/POST/Pub/PersonPrograms',
                    destroy: '/Pub/PersonPrograms'
                },
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            }
        }
    }

});