/*
 * File: app/view/HomePage.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('eLearning.view.HomePage', {
    extend: 'Ext.container.Container',
    alias: 'widget.homepage',

    requires: [
        'eLearning.view.HomePageViewModel',
        'Ext.button.Button',
        'Ext.container.Container',
        'Ext.form.Label'
    ],

    viewModel: {
        type: 'homepage'
    },
    itemId: 'homePage',
    defaults: {
        width: 200,
        height: 50,
        margin: 5
    },

    layout: {
        type: 'vbox',
        align: 'center',
        pack: 'center'
    },
    items: [
        {
            xtype: 'button',
            handler: function(button, e) {
                this.up('#mainView').setActiveItem('gridPrograms');
            },
            text: 'Training Programs'
        },
        {
            xtype: 'button',
            handler: function(button, e) {

            },
            text: 'Help'
        },
        {
            xtype: 'container',
            height: 200,
            defaults: {
                flex: 1
            },
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'label',
                    flex: 0,
                    height: 20,
                    text: 'DEV / DEBUG / TEST'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        var TEMP_ID = "{01A26F88-5649-4693-9227-28E8E2F7A963}";

                        var mainView = this.up('#mainView');
                        var newActiveItem = mainView.setActiveItem('editSlides');

                        var localStorageData = Ext.decode(localStorage.getItem('mxp_elearning'));
                        console.log("printing localstorage", localStorageData);

                        if(!localStorageData){
                            localStorageData = {};
                        }
                        if(!localStorageData[TEMP_ID]){
                            localStorageData[TEMP_ID] = {};
                        }
                        for (var key in localStorageData[TEMP_ID]) {
                            if(!localStorageData[TEMP_ID][key]){
                                localStorageData[TEMP_ID][key]={};
                            }
                        }
                        localStorage.setItem('mxp_elearning', Ext.encode(localStorageData));

                        newActiveItem.getController().load({ program :{id :TEMP_ID} }); // with programId
                    },
                    text: 'Edit Slides'
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        Ext.toast('This is a toast message');
                    },
                    text: 'Test'
                }
            ]
        }
    ]

});