/*
 * File: app/view/Templates.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('eLearning.view.Templates', {
    extend: 'Ext.window.Window',
    alias: 'widget.templates',

    requires: [
        'eLearning.view.TemplatesViewModel'
    ],

    viewModel: {
        type: 'templates'
    },
    modal: true,
    height: 600,
    width: 1000,
    title: 'Templates'

});